### PR TITLE
Fix behaviour of 'If Message Delivery Fails'

### LINKED ISSUE #629: Check if delivery fails on send message action does not work, it does not get triggerd -no errors
**Describe the bug**
The Check if delivery fails on the send message action does not work. It won't get triggered. Would be cool if this can be fixed.

**To Reproduce**
1. Create command/event'
2. build a command/event that sends a message  '....'
3. build diffrent actions in this command / event and the bot needs to send a message  '....'
4. Create some actions that will triggerd if the message failed to send and set the action to jump to it on the send message action
5. Run the command/event, test it out by removing the bot perms to channel where the bot need to send it by the channel id
(of course find channel is in your event/command)
6. or delete the channel and try let the bot send the message

There is no error printing into the console

**Expected behavior**
The bot should jump to the action(s) and execute them but nothing happens, no errors nothing.

### PR DESCRIPTION
**Pull request by tlfn**
**Please describe the changes this PR makes and why it should be merged:**
This changes issue Failed trigger whatever the reason for fail was.
It closes #629 

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by tlfn** [comment]
How do you think about triggering Delivery Failed when `target.send` does not exist?

**Review by TheMonDon — APPROVED** [review]

File: actions/send_embed_message.js [hunk 1]
```diff
@@ -118,12 +118,8 @@ module.exports = {
...
         })
-        .catch((err) => {
-          if (err.message === 'Cannot send messages to this user') {
-            this.executeResults(false, data, cache)
-          } else {
-            this.displayError.bind(this, data, cache)
-          }
+        .catch(() => {
+          this.executeResults(false, data, cache)
         })
```
Comment (almeidx) [inline actions/send_embed_message.js:123]:
```suggestion
        .catch(() => this.executeResults(false, data, cache))
```

File: actions/send_message.js [hunk 2]
```diff
@@ -118,12 +118,8 @@ module.exports = {
...
         })
-        .catch((err) => {
-          if (err.message === 'Cannot send messages to this user') {
-            this.executeResults(false, data, cache)
-          } else {
-            this.displayError.bind(this, data, cache)
-          }
+        .catch(() => {
+          this.executeResults(false, data, cache)
         })
```
Comment (almeidx) [inline actions/send_message.js:123]:
```suggestion
        .catch(() => this.executeResults(false, data, cache))
```

**Review by almeidx — CHANGES_REQUESTED** [review]

**Review by almeidx — APPROVED** [review]
